system:
  version: 3.0
config:
  info: "this is config dev enm, good for you"
server:
  port: 3355
spring:
  application:
    name: config-client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
